sudo: false
cache: pip

addons:
  postgresql: "9.6"
  ssh_known_hosts: 157.245.80.19
  sonarcloud:
    organization: "fhirsistemsalud"
    token:
      secure:  "V8dbFshZpHs7DVDsBo8PttZqZHzPSR4s9EwZBJvQ7hN1IbuLk1CG5+pd/WqFbBdoc5W+sHxnvb64NC29dpgmsxNmUZNhnxBdnkOR3N3ZGIiYDnzyhLZ9OyvtaCWvIYpdV8pEqbNX+POe/AmiMG8QEFBxvZvMfNRHmDDbVdOGXNlTsjLL+qqbOyDv+WnAVPYkdbkpGIFRh9/d6bRBz5kDTqj/iEVo7Pnu5HWkLjyoFLuu8iSLIkP6RtFpKZF5LCY1OSqxPgnd6cIrANigDuHHNn2TfwJb7BKE55ZJKWUThMp7/1y3A0L4RwvXVmBHnfAwkE4sU4J95S3gwklZ+ncInNe1rd5f/vCJCSBsyfoKSYTueCzu6o+t8duupKJxns8NkMylo+a5J888oOsLiNGtwn4JUfWRSdkcwTHpPRdD27LGLeiyRNwxaIcece9UF+1mL/L9DZ2Q4LFxeseRkGlRN+nm0E9Z6mjwdfFOXrJ+vVsbM67Xg3RQJgNSZS8BbshU0GLDyT0VSdOkU+/KomxPZru5qV28J/mluPeAu0BkirGzXz6DF8lMOZRFQc7Wznt/2mRmtIv4RZpJYXUmG+Ah+oCMTeVS6xDY3PU85qeuCOSkNCtTeYIt9IpvHCxaAPgSBQt1d9oMBcMf1KP7HIt7cmpJbHexN1dc5AAKkz0A/Rw="
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

language: python

python:
  - "3.5"

stages:
    - linting
    - test

jobs:
  include:
    - stage: linting
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB"

env:
  global:
    - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

install:
  - openssl aes-256-cbc -k $encrypted_key -in fhir.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_tests


after_success:
  - travis_after_tests_success
  - sonar-scanner # Ejecutar analisis sonar despues de pruebas Odoo-Travis. Evitar Problemas de Covertura incompleta
  - ssh deploy@157.245.80.19 /home/deploy/update.sh
  - ssh deploy@157.245.80.19 sudo /home/deploy/autodeploy.sh